# By knightfall01 as a part of https://github.com/Knightfall01/Hyprland-i3

[nodejs]
format = 'on [ğŸ€ $version](bold green)'

[python]
format = 'on [îˆµ  $version](bold yellow)'

[character]
success_symbol = "[ï‘ ï”](bold green)"

